export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const TOGGLE_CART_OPEN = "TOGGLE_CART_OPEN";
export const TOGGLE_CART_CLOSE = "TOGGLE_CART_CLOSE";
